### ISSUE TITLE
a

### ISSUE THREAD

**Issue by vlerenc** [gardener/hub#1]

**Comment by gardener-botmanager** [comment]
@vlerenc Label "aaaaa" does not exist for this repository.

**Comment by gardener-botmanager** [comment]
@vlerenc Milestone "sss" does not exist for this repository.

**Comment by gardener-botmanager** [comment]
@vlerenc Label "aaaa" does not exist for this repository.

**Comment by gardener-botmanager** [comment]
@vlerenc Label "milestone" does not exist for this repository.

**Comment by gardener-botmanager** [comment]
@vlerenc Label "milestone" does not exist for this repository.

**Comment by gardener-botmanager** [comment]
@vlerenc Label "aaaa" does not exist for this repository.

**Comment by vlerenc** [comment]
/cc @rfranzke 

Label removal is now idempotent.

**Comment by vlerenc** [comment]
/cc @ialidzhikov 

`/cc` on issues will now be silently ignored.

**Comment by gardener-botmanager** [comment]
@ialidzhikov 
<img src="https://source.unsplash.com/collection/1120118/640x425">
<details>
<summary>Message</summary>

> /bark
</details>

**Comment by vlerenc** [comment]
/xs
/diag https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-vlerenc/shoots/cc

**Comment by vlerenc** [comment]
/duplicate https://github.tools.sap/kubernetes/gardener-robot/issues/17

**Comment by vlerenc** [comment]
/duplicate https://github.tools.sap/kubernetes/gardener-robot/issues/17

**Comment by vlerenc** [comment]
/duplicate https://github.tools.sap/kubernetes/gardener-robot/issues/17

**Comment by vlerenc** [comment]
/duplicate https://github.tools.sap/kubernetes/gardener-robot/issues/17
